"""drop orphaned generation_job table, make reference display names non-nullable

Revision ID: 3aa83be21d1e
Revises: 6c71c83ad4a0
Create Date: 2026-09-19 17:25:30.592578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.db.models.types
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3aa83be21d1e'
down_revision: Union[str, Sequence[str], None] = '6c71c83ad4a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # generation_job is a leftover from a fully-reverted feature (commit
    # 87bad3f) whose old add-table migration was deleted without a
    # corresponding drop-table migration ever being added — so whether it
    # exists on a given database depends only on whether that feature
    # happened to be deployed there before the revert, not on anything
    # tracked by a migration number. IF EXISTS (dropping the table cascades
    # to its indexes) makes this migration safe to run unconditionally
    # across every environment regardless of that history.
    op.execute("DROP TABLE IF EXISTS generation_job CASCADE")
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('malayalam_masa', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('malayalam_masa', 'en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('nakshatra', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('nakshatra', 'en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('paksha', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('paksha', 'en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('thithi', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('thithi', 'en',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thithi', 'en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('thithi', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('paksha', 'en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('paksha', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('nakshatra', 'en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('nakshatra', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('malayalam_masa', 'en',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('malayalam_masa', 'ml',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_table('generation_job',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('job_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('lock_key', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('params', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('progress', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('started_by', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('generation_job_pkey')),
    sa.UniqueConstraint('lock_key', name=op.f('uq_generation_job_lock_key'))
    )
    op.create_index(op.f('ix_generation_job_status'), 'generation_job', ['status'], unique=False)
    op.create_index(op.f('ix_generation_job_job_type'), 'generation_job', ['job_type'], unique=False)
    # ### end Alembic commands ###
