"""baseline schema

Revision ID: 6c71c83ad4a0
Revises: 
Create Date: 2026-09-19 16:19:46.732886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
import app.db.models.types


# revision identifiers, used by Alembic.
revision: str = '6c71c83ad4a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_setting',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', app.db.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('chandra_masa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ml', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('dataset_etag',
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('etag', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', app.db.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('guruvani',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_ml', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guruvani_sort_order'), 'guruvani', ['sort_order'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('label', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_location_name'), 'location', ['name'], unique=True)
    op.create_table('malayalam_masa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ml', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('nakshatra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ml', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('paksha',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ml', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('thithi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('paksha_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Integer(), nullable=False),
    sa.Column('ml', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['paksha_id'], ['paksha.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('panchangam',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('thithi_id', sa.Integer(), nullable=False),
    sa.Column('nakshatra_id', sa.Integer(), nullable=False),
    sa.Column('nazhika_from_sunrise', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['nakshatra_id'], ['nakshatra.id'], ),
    sa.ForeignKeyConstraint(['thithi_id'], ['thithi.id'], ),
    sa.PrimaryKeyConstraint('date', 'location_id')
    )
    op.create_table('santhigiri_event',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('nakshatra_id', sa.Integer(), nullable=True),
    sa.Column('thithi_id', sa.Integer(), nullable=True),
    sa.Column('ml_day', sa.Integer(), nullable=True),
    sa.Column('ml_month', sa.Integer(), nullable=True),
    sa.Column('ml_year', sa.Integer(), nullable=True),
    sa.Column('chandra_masa_day', sa.Integer(), nullable=True),
    sa.Column('chandra_masa_month', sa.Integer(), nullable=True),
    sa.Column('en_day', sa.Integer(), nullable=True),
    sa.Column('en_month', sa.Integer(), nullable=True),
    sa.Column('en_year', sa.Integer(), nullable=True),
    sa.Column('occurance', sa.Integer(), nullable=True),
    sa.Column('is_poornima', sa.Boolean(), nullable=True),
    sa.Column('last_occurance', sa.Boolean(), nullable=True),
    sa.Column('day_offset', sa.Integer(), nullable=True),
    sa.Column('yields_to_event_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['nakshatra_id'], ['nakshatra.id'], ),
    sa.ForeignKeyConstraint(['thithi_id'], ['thithi.id'], ),
    sa.ForeignKeyConstraint(['yields_to_event_id'], ['santhigiri_event.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_santhigiri_event_sort_order'), 'santhigiri_event', ['sort_order'], unique=False)
    op.create_table('chandra_masa_date',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('masa_id', sa.Integer(), nullable=False),
    sa.Column('masa_day', sa.Integer(), nullable=False),
    sa.Column('masa_type', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date', 'location_id'], ['panchangam.date', 'panchangam.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['masa_id'], ['chandra_masa.id'], ),
    sa.PrimaryKeyConstraint('date', 'location_id')
    )
    op.create_table('kollavarsham_date',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('kv_day', sa.Integer(), nullable=False),
    sa.Column('kv_month', sa.Integer(), nullable=False),
    sa.Column('kv_year', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['date', 'location_id'], ['panchangam.date', 'panchangam.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['kv_month'], ['malayalam_masa.id'], ),
    sa.PrimaryKeyConstraint('date', 'location_id')
    )
    op.create_table('nakshatra_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panchangam_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('nakshatra_id', sa.Integer(), nullable=False),
    sa.Column('start_time', app.db.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_time', app.db.models.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['nakshatra_id'], ['nakshatra.id'], ),
    sa.ForeignKeyConstraint(['panchangam_date', 'location_id'], ['panchangam.date', 'panchangam.location_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nakshatra_transitions_date', 'nakshatra_transitions', ['panchangam_date', 'location_id', 'start_time'], unique=False)
    op.create_table('santhigiri_event_dates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panchangam_date', sa.Date(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['santhigiri_event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_santhigiri_event_dates_date', 'santhigiri_event_dates', ['panchangam_date'], unique=False)
    op.create_index(op.f('ix_santhigiri_event_dates_event_id'), 'santhigiri_event_dates', ['event_id'], unique=False)
    op.create_table('sunrise_sunset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('sunrise', app.db.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sunset', app.db.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['date', 'location_id'], ['panchangam.date', 'panchangam.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'location_id', name='uq_sunrise_sunset_date_loc')
    )
    op.create_index('idx_sunrise_sunset_date', 'sunrise_sunset', ['date'], unique=False)
    op.create_table('thithi_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('panchangam_date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('thithi_id', sa.Integer(), nullable=False),
    sa.Column('start_time', app.db.models.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_time', app.db.models.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['panchangam_date', 'location_id'], ['panchangam.date', 'panchangam.location_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['thithi_id'], ['thithi.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_thithi_transitions_date', 'thithi_transitions', ['panchangam_date', 'location_id', 'start_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_thithi_transitions_date', table_name='thithi_transitions')
    op.drop_table('thithi_transitions')
    op.drop_index('idx_sunrise_sunset_date', table_name='sunrise_sunset')
    op.drop_table('sunrise_sunset')
    op.drop_index(op.f('ix_santhigiri_event_dates_event_id'), table_name='santhigiri_event_dates')
    op.drop_index('idx_santhigiri_event_dates_date', table_name='santhigiri_event_dates')
    op.drop_table('santhigiri_event_dates')
    op.drop_index('idx_nakshatra_transitions_date', table_name='nakshatra_transitions')
    op.drop_table('nakshatra_transitions')
    op.drop_table('kollavarsham_date')
    op.drop_table('chandra_masa_date')
    op.drop_index(op.f('ix_santhigiri_event_sort_order'), table_name='santhigiri_event')
    op.drop_table('santhigiri_event')
    op.drop_table('panchangam')
    op.drop_table('thithi')
    op.drop_table('paksha')
    op.drop_table('nakshatra')
    op.drop_table('malayalam_masa')
    op.drop_index(op.f('ix_location_name'), table_name='location')
    op.drop_table('location')
    op.drop_index(op.f('ix_guruvani_sort_order'), table_name='guruvani')
    op.drop_table('guruvani')
    op.drop_table('dataset_etag')
    op.drop_table('chandra_masa')
    op.drop_table('app_setting')
    # ### end Alembic commands ###
